spring:
  datasource:
    username: root
    password: 111222
    url: jdbc:mysql://localhost:3306/use_rent
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
