spring.application.name=nacos-8002
server.port=8002
# \u670D\u52A1\u53D1\u73B0\uFF08\u6CE8\u518C/\u627E\u670D\u52A1\uFF09
spring.cloud.nacos.discovery.server-addr=192.168.80.128:8848
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos
spring.cloud.nacos.discovery.cluster-name=BJ
# \u8D1F\u8F7D\u5747\u8861
spring.cloud.loadbalancer.nacos.enabled=true
# feign\u65E5\u5FD7
spring.cloud.openfeign.client.config.default.logger-level=FULL
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=10000
spring.cloud.openfeign.httpclient.hc5.enabled=true
spring.cloud.openfeign.httpclient.max-connections=200
spring.cloud.openfeign.httpclient.max-connections-per-route=50
# \u914D\u7F6E\u4E2D\u5FC3
spring.config.import=optional:nacos:calendar.yaml
spring.cloud.nacos.config.server-addr=192.168.80.128:8848
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos
