spring.application.name=nacos-8002
server.port=8002
# 服务发现（注册/找服务）
spring.cloud.nacos.discovery.server-addr=192.168.80.128:8848
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos
spring.cloud.nacos.discovery.cluster-name=BJ
# 负载均衡：全局开启 NacosLoadBalancer（同集群优先 + 权重）
# 若要按服务名局部配置，可把此行设为 false，然后通过
# @LoadBalancerClient(name = "nacos-8001", configuration = ...) 注解为特定服务开启
spring.cloud.loadbalancer.nacos.enabled=true
# 配置中心
spring.cloud.nacos.config.server-addr=192.168.80.128:8848
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos
