#\u914D\u7F6E\u9759\u6001\u8D44\u6E90\u8DEF\u5F84
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
#ant\u98CE\u683C\u8DEF\u5F84\u5339\u914D
spring.mvc.pathmatch.matching-strategy=path_pattern_parser
#\u4FE1\u606F\u8FD4\u56DE
spring.mvc.contentnegotiation.favor-parameter=true
#\u6574\u5408Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html




