spring.application.name=springboot
spring.config.import=classpath:/config/application-one.properties,classpath:/config/application-two.properties
prefile.id=1
prefile.name=prefile
#\u591A\u73AF\u5883\u914D\u7F6E\u6587\u4EF6
spring.profiles.active=dev
