
id=1
name=properties
#-------------------------------------------
user.id=1
user.name=bean
#---------------------------------------------
# \u6570\u7EC4\u914D\u7F6E
collection.names=\u5F20\u4E09,\u674E\u56DB,\u738B\u4E94

# \u5BF9\u8C61\u914D\u7F6E
collection.user[0].id=1
collection.user[0].name=101
collection.user[1].id=2
collection.user[1].name=102

# List\u914D\u7F6E
collection.list=\u82F9\u679C,\u9999\u8549,\u6A59\u5B50

# Map\u914D\u7F6E
collection.map.one=value1
collection.map.two=value2
collection.map.three=value3

