#@Value configuration
value.id=1
value.name=value
#---------------------------------------------
#Collection configuration
# \u57FA\u672C\u7C7B\u578B
collection.names=\u5F20\u4E09,\u674E\u56DB,\u738B\u4E94
# \u5BF9\u8C61\u914D\u7F6E
collection.stu[0].id=1
collection.stu[0].name=101
collection.stu[1].id=2
collection.stu[1].name=102
# List\u96C6\u5408
collection.list=\u82F9\u679C,\u9999\u8549,\u6A59\u5B50
# Map\u96C6\u5408
collection.map.one=value1
collection.map.two=value2
collection.map.three=value3
#----------------------------------------
# \u590D\u6742 Configuration
# A pro
address.building=one
# A
address.room.className=\u4E09\u5E74\u4E00\u73ED
address.room.location=\u4E00\u697C
#----------------------------------------
#Out\u548COuter
outer.name=\u7B2C\u4E09\u65B9\u623F\u95F4
outer.age=18




