spring.application.name=nacos-8003
server.port=8003
# \u670D\u52A1\u53D1\u73B0\uFF08\u6CE8\u518C/\u627E\u670D\u52A1\uFF09
spring.cloud.nacos.discovery.server-addr=192.168.80.128:8848
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos
spring.cloud.nacos.discovery.cluster-name=SH

spring.cloud.loadbalancer.nacos.enabled=true
# \u914D\u7F6E\u4E2D\u5FC3
spring.cloud.nacos.config.server-addr=192.168.80.128:8848
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos
